id: P006863
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20233
  title: ཇོ་མོ་གླང་མའི་བོད་ཡིག་ཡིག་གཟུགས།
  author: ''
  volumes:
    39787cae4662403787e05c41e7f876df:
      image_group_id: I8LS20235
      title: ''
      volume_number: 1
      total_pages: 147
